language: python

python: 2.7

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - /.*/

 # Use container-based infrastructure
sudo: false

install:
  - npm install

script:
  - grunt
